/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nwpu_aslp_wakeup_NdkJniUtils */

#ifndef _Included_nwpu_aslp_wakeup_NdkJniUtils
#define _Included_nwpu_aslp_wakeup_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nwpu_aslp_wakeup_NdkJniUtils
 * Method:    pcm2fbank
 * Signature: ([SI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_nwpu_1aslp_wakeup_NdkJniUtils_pcm2fbank
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     nwpu_aslp_wakeup_NdkJniUtils
 * Method:    initDnn
 * Signature: ([[F[[F[[F[[F[F[F[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_nwpu_1aslp_wakeup_NdkJniUtils_initDnn
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     nwpu_aslp_wakeup_NdkJniUtils
 * Method:    getdnn
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_nwpu_1aslp_wakeup_NdkJniUtils_getdnn
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
